# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_design_medium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
    ]
